/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2.estructura.de.datos.jc.sh;

import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class principal extends javax.swing.JFrame {

	DefaultListModel<String> modeloUsuarios = new DefaultListModel<>();
	TablaDispersion MiTablaHash = new TablaDispersion();
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(principal.class.getName());

	/**
	 * Creates new form principal
	 */
	public principal() {
		initComponents();
		ListadeUsuarios.setModel(modeloUsuarios);
		DefaultTableModel modeloTablaDocs = new DefaultTableModel();
		modeloTablaDocs.addColumn("Nombre");
		modeloTablaDocs.addColumn("Tamaño (págs)");
		modeloTablaDocs.addColumn("Tipo");
		modeloTablaDocs.addColumn("Estado"); // Para saber si está en cola o no 
		jTable1.setModel(modeloTablaDocs);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton6 = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                ListadeUsuarios = new javax.swing.JList<>();
                CargarCSV = new javax.swing.JButton();
                AgregarUsuario = new javax.swing.JButton();
                EliminarUsuarios = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                CrearDoc = new javax.swing.JButton();
                EliminarDoc = new javax.swing.JButton();
                MnadarImprimir = new javax.swing.JButton();
                jCheckBox1 = new javax.swing.JCheckBox();
                jPanel2 = new javax.swing.JPanel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                MostrarArbol = new javax.swing.JPanel();
                VistaLista = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();

                jButton6.setText("jButton6");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(255, 255, 255));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de Usuarios"));

                ListadeUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                });
                ListadeUsuarios.addListSelectionListener(this::ListadeUsuariosValueChanged);
                jScrollPane1.setViewportView(ListadeUsuarios);

                CargarCSV.setText("Cargar CSV");
                CargarCSV.addActionListener(this::CargarCSVActionPerformed);

                AgregarUsuario.setText("[+] Agregar Usuario");
                AgregarUsuario.addActionListener(this::AgregarUsuarioActionPerformed);

                EliminarUsuarios.setText("[-] Eliminar Usuario");
                EliminarUsuarios.addActionListener(this::EliminarUsuariosActionPerformed);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(EliminarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AgregarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                        .addComponent(CargarCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CargarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(AgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                );

                getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 610));

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Documentos Del Usuario Selccionado"));

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane2.setViewportView(jTable1);

                CrearDoc.setText("Crear Doc");
                CrearDoc.addActionListener(this::CrearDocActionPerformed);

                EliminarDoc.setText("Eliminar Doc");
                EliminarDoc.addActionListener(this::EliminarDocActionPerformed);

                MnadarImprimir.setText("Mandar a imprimir");
                MnadarImprimir.addActionListener(this::MnadarImprimirActionPerformed);

                jCheckBox1.setText("Es prioritario");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(EliminarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MnadarImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1)
                                .addContainerGap(50, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(CrearDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(451, Short.MAX_VALUE)))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EliminarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MnadarImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox1))
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap(258, Short.MAX_VALUE)
                                        .addComponent(CrearDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap()))
                );

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 610, 320));

                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cola de Impresion"));

                MostrarArbol.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout MostrarArbolLayout = new javax.swing.GroupLayout(MostrarArbol);
                MostrarArbol.setLayout(MostrarArbolLayout);
                MostrarArbolLayout.setHorizontalGroup(
                        MostrarArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 588, Short.MAX_VALUE)
                );
                MostrarArbolLayout.setVerticalGroup(
                        MostrarArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 158, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Vista Arbol", MostrarArbol);

                VistaLista.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout VistaListaLayout = new javax.swing.GroupLayout(VistaLista);
                VistaLista.setLayout(VistaListaLayout);
                VistaListaLayout.setHorizontalGroup(
                        VistaListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 588, Short.MAX_VALUE)
                );
                VistaListaLayout.setVerticalGroup(
                        VistaListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 158, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Vista Lista", VistaLista);

                jButton1.setText("Liberar Impresora");

                jButton5.setText("Cancelar en cola");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTabbedPane1)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)))
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton5))
                                .addGap(15, 15, 15))
                );

                jTabbedPane1.getAccessibleContext().setAccessibleName("Vista Del Arbol");
                jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

                getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 610, 280));

                pack();
        }// </editor-fold>//GEN-END:initComponents
	/**
	 * Metodo espondable del funcionamiento del boton de eliminar Documento
	 * utiliza el jTable1 para seleccionar el docuemnto y luego al darle al boton de "borrar doc" se borra.
	 */
        private void EliminarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDocActionPerformed
		// TODO add your handling code here:
		int fila = jTable1.getSelectedRow();
		if (fila == -1) { // en caso de no seleccionar en la lista sale este mensaje
			JOptionPane.showMessageDialog(this, "Seleccione un documento de la tabla.");
			return;
		}
		// logica en caso de que el documento este en cola de impresion
		String nombreDoc = jTable1.getValueAt(fila, 0).toString();
		String estado = jTable1.getValueAt(fila, 3).toString();
		if (estado.equals("En Cola")) {
			JOptionPane.showMessageDialog(this, "No puede eliminar un documento que ya está en la cola de impresión desde aquí.\nUse la función 'Cancelar en cola'.");
			return;
		}
		// logica de eliminacion
		int userIndice = ListadeUsuarios.getSelectedIndex();
		String item = modeloUsuarios.getElementAt(userIndice);
		String nombreUser = item.split(" \\(")[0].trim();
		Usuario user = MiTablaHash.buscarUsuario(nombreUser);

		if (user != null) {
			int confirmar = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar '" + nombreDoc + "'?");
			if (confirmar == JOptionPane.YES_OPTION) {
				if (user.eliminarDocumentoDeLista(nombreDoc)) {
					actualizarTablaDocumentos(user); // Refrescar la tabla visual
					JOptionPane.showMessageDialog(this, "Documento eliminado.");
				}
			}
		}
        }//GEN-LAST:event_EliminarDocActionPerformed

        private void MnadarImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnadarImprimirActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_MnadarImprimirActionPerformed

        private void CargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarCSVActionPerformed
		// TODO add your handling code here:
		ManejoDeArchivos manejador = new ManejoDeArchivos();
		String[][] datosUsuarios = manejador.cargarUsuarios(this);
		if (datosUsuarios != null) {
			for (int i = 0; i < datosUsuarios.length; i++) {
				String nombre = datosUsuarios[i][0];
				String tipo = datosUsuarios[i][1];
				Usuario nuevoUsuario = new Usuario(nombre, tipo);
				MiTablaHash.agregarUsuario(nombre, tipo, nuevoUsuario);
				modeloUsuarios.addElement(nombre + " (" + tipo + " )");
			}
			JOptionPane.showMessageDialog(this, "se cargaron " + datosUsuarios.length + " usuarios exitosamente.", "Carga completa", JOptionPane.INFORMATION_MESSAGE);
		} else {
			String Error = manejador.getUltimoError();

			if (!Error.equals("Carga cancelada por el usuario.")) {
				JOptionPane.showMessageDialog(this, Error, "Error de formato", JOptionPane.ERROR_MESSAGE);
			}
		}
        }//GEN-LAST:event_CargarCSVActionPerformed

        private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
		// TODO add your handling code here:
		String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del nuevo usuario: ", "Nuevo Usuario", JOptionPane.QUESTION_MESSAGE);
		if (nombre == null) {
			return;
		}
		nombre = nombre.trim();
		if (nombre.isEmpty()) {
			JOptionPane.showMessageDialog(this, "El nombre del usuario no puede estar vacio..", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
		String[] opciones = {"prioridad alta", "prioridad media", "prioridad baja"};

		String tipo = (String) JOptionPane.showInputDialog(this,
			"Seleccione la prioridad para " + nombre + ":",
			"Seleccionar Prioridad",
			JOptionPane.QUESTION_MESSAGE,
			null,
			opciones,
			opciones[0]
		);

		if (tipo != null) {

			if (MiTablaHash.existeUsuario(nombre)) {
				JOptionPane.showMessageDialog(this, "El usuario '" + nombre + "' ya existe.", "Error", JOptionPane.WARNING_MESSAGE);
			} else {
				Usuario nuevo = new Usuario(nombre, tipo);
				MiTablaHash.agregarUsuario(nombre, tipo, nuevo);
				modeloUsuarios.addElement(nuevo.getNombre() + " (" + nuevo.getTipo() + ")");
				JOptionPane.showMessageDialog(this, "Usuario registrado con éxito.");
			}
		}
        }//GEN-LAST:event_AgregarUsuarioActionPerformed

        private void CrearDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearDocActionPerformed
		// TODO add your handling code here:
		int seleccionado = ListadeUsuarios.getSelectedIndex();
		if (seleccionado == -1) {
			JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario de la lista.");
			return;
		}

		String item = modeloUsuarios.getElementAt(seleccionado);
		String nombreUsuario = item.split(" \\(")[0]; // Extrae el nombre antes del paréntesis
		String nombreDoc = JOptionPane.showInputDialog(this, "Nombre del documento:");
		if (nombreDoc == null || nombreDoc.trim().isEmpty()) {
			return;
		}

		String tamañoStr = JOptionPane.showInputDialog(this, "Tamaño (páginas):");
		int tamaño;
		try {
			tamaño = Integer.parseInt(tamañoStr);
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this, "El tamaño debe ser un número.");
			return;
		}

		String tipoDoc = JOptionPane.showInputDialog(this, "Tipo (PDF, DOCX, etc):");
		Usuario user = MiTablaHash.buscarUsuario(nombreUsuario);

		if (user != null) {
			NodoDocumento nuevo = new NodoDocumento(nombreDoc, tamaño, tipoDoc, 0, false, nombreUsuario);
			user.agregarDocumento(nuevo);
			actualizarTablaDocumentos(user);
			JOptionPane.showMessageDialog(this, "Documento '" + nombreDoc + "' agregado a la carpeta de " + nombreUsuario);
		}

        }//GEN-LAST:event_CrearDocActionPerformed

        private void EliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuariosActionPerformed
		// TODO add your handling code here:
		int indiceSeleccionado = ListadeUsuarios.getSelectedIndex();

		if (indiceSeleccionado == -1) {
			JOptionPane.showMessageDialog(this, "Seleccione un usuario de la lista para eliminarlo.", "Aviso", JOptionPane.WARNING_MESSAGE);
			return;
		}
		String textoCompleto = modeloUsuarios.getElementAt(indiceSeleccionado);
		String nombreUsuario = textoCompleto.split(" \\(")[0];

		int confirmar = JOptionPane.showConfirmDialog(this,
			"¿Seguro que desea eliminar a '" + nombreUsuario + "'?\nEsto borrará todos sus documentos.",
			"Confirmar eliminación", JOptionPane.YES_NO_OPTION);

		if (confirmar == JOptionPane.YES_OPTION) {
			boolean eliminadoDeHash = MiTablaHash.eliminarUsuario(nombreUsuario);
			if (eliminadoDeHash) {
				modeloUsuarios.remove(indiceSeleccionado);
				JOptionPane.showMessageDialog(this, "Usuario '" + nombreUsuario + "' eliminado con éxito.");
			} else {
				JOptionPane.showMessageDialog(this, "Error: El usuario no existía en la estructura de datos.");
			}
		}
        }//GEN-LAST:event_EliminarUsuariosActionPerformed

        private void ListadeUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListadeUsuariosValueChanged
		// TODO add your handling code here:
		if (!evt.getValueIsAdjusting()) {
			int indice = ListadeUsuarios.getSelectedIndex();
			if (indice != -1) {
				String texto = modeloUsuarios.getElementAt(indice);
				String nombre = texto.split(" \\(")[0].trim();
				Usuario user = MiTablaHash.buscarUsuario(nombre);
				actualizarTablaDocumentos(user);
			}
		}
        }//GEN-LAST:event_ListadeUsuariosValueChanged

	// Metodo auxiliares:
	/**
	 * Metodo Necesario para mostrar los documentos en el jTable1 sin este
	 * solo se guardaria el documento en memoria
	 *
	 * @param user por cada usuario tiene sus documentos
	 */
	public void actualizarTablaDocumentos(Usuario user) {
		DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
		modelo.setRowCount(0);

		if (user == null) {
			return;
		}

		NodoDocumento actual = user.getPrimerDocumento();

		while (actual != null) {
			String estado = actual.isEnCola() ? "En Cola" : "Pendiente";

			modelo.addRow(new Object[]{
				actual.getNombre(),
				actual.getTamaño(),
				actual.getTipo(),
				estado
			});

			actual = actual.getSiguiente();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new principal().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton AgregarUsuario;
        private javax.swing.JButton CargarCSV;
        private javax.swing.JButton CrearDoc;
        private javax.swing.JButton EliminarDoc;
        private javax.swing.JButton EliminarUsuarios;
        private javax.swing.JList<String> ListadeUsuarios;
        private javax.swing.JButton MnadarImprimir;
        private javax.swing.JPanel MostrarArbol;
        private javax.swing.JPanel VistaLista;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTable jTable1;
        // End of variables declaration//GEN-END:variables
}
