/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2.estructura.de.datos.jc.sh;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/**
 *
 * @author andre
 */
public class principal extends javax.swing.JFrame {
	DefaultListModel<String> modeloUsuarios = new DefaultListModel<>();
	TablaDispersion MiTablaHash = new TablaDispersion();
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(principal.class.getName());

	/**
	 * Creates new form principal
	 */
	public principal() {
		initComponents();
		ListadeUsuarios.setModel(modeloUsuarios);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel3 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                ListadeUsuarios = new javax.swing.JList<>();
                CargarCSV = new javax.swing.JButton();
                AgregarUsuario = new javax.swing.JButton();
                EliminarUsuario = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();
                jCheckBox1 = new javax.swing.JCheckBox();
                jPanel2 = new javax.swing.JPanel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                MostrarArbol = new javax.swing.JPanel();
                VistaLista = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(255, 255, 255));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de Usuarios"));

                ListadeUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                });
                jScrollPane1.setViewportView(ListadeUsuarios);

                CargarCSV.setText("Cargar CSV");
                CargarCSV.addActionListener(this::CargarCSVActionPerformed);

                AgregarUsuario.setText("[+] Agregar Usuario");
                AgregarUsuario.addActionListener(this::AgregarUsuarioActionPerformed);

                EliminarUsuario.setText("[-] Eliminar Usuario");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addComponent(CargarCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AgregarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                        .addComponent(EliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CargarCSV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(AgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 590));

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Documentos Del Usuario Selccionado"));

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane2.setViewportView(jTable1);

                jButton2.setText("Crear Doc");

                jButton3.setText("Eliminar Doc");
                jButton3.addActionListener(this::jButton3ActionPerformed);

                jButton4.setText("Mandar a imprimir");
                jButton4.addActionListener(this::jButton4ActionPerformed);

                jCheckBox1.setText("Es prioritario");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1)
                                .addContainerGap(50, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(451, Short.MAX_VALUE)))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox1))
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap(258, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap()))
                );

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 610, 320));

                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cola de Impresion"));

                MostrarArbol.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout MostrarArbolLayout = new javax.swing.GroupLayout(MostrarArbol);
                MostrarArbol.setLayout(MostrarArbolLayout);
                MostrarArbolLayout.setHorizontalGroup(
                        MostrarArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 588, Short.MAX_VALUE)
                );
                MostrarArbolLayout.setVerticalGroup(
                        MostrarArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 158, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Vista Arbol", MostrarArbol);

                VistaLista.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout VistaListaLayout = new javax.swing.GroupLayout(VistaLista);
                VistaLista.setLayout(VistaListaLayout);
                VistaListaLayout.setHorizontalGroup(
                        VistaListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 588, Short.MAX_VALUE)
                );
                VistaListaLayout.setVerticalGroup(
                        VistaListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 158, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Vista Lista", VistaLista);

                jButton1.setText("Liberar Impresora");

                jButton5.setText("Cancelar en cola");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTabbedPane1)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton5))
                                .addContainerGap())
                );

                jTabbedPane1.getAccessibleContext().setAccessibleName("Vista Del Arbol");
                jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

                getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 610, 260));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton3ActionPerformed

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton4ActionPerformed

        private void CargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarCSVActionPerformed
                // TODO add your handling code here:
		ManejoDeArchivos  manejador = new ManejoDeArchivos();
		String[][] datosUsuarios = manejador.cargarUsuarios(this);
		if(datosUsuarios != null){
			for (int i = 0; i< datosUsuarios.length; i++){
				String nombre = datosUsuarios[i][0];
				String tipo = datosUsuarios[i][1];
				//MiTablaHash.agregar(nombre, tipo);
				modeloUsuarios.addElement(nombre + " (" + tipo + " )");
			}
			JOptionPane.showMessageDialog(this, "se cargaron " + datosUsuarios.length + " usuarios exitosamente.", "Carga completa", JOptionPane.INFORMATION_MESSAGE);
		} else{
			String Error = manejador.getUltimoError();
			
			if(!Error.equals("Carga cancelada por el usuario.")){
				JOptionPane.showMessageDialog(this, Error, "Error de formato", JOptionPane.ERROR_MESSAGE);
			}
		}
        }//GEN-LAST:event_CargarCSVActionPerformed

        private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
                // TODO add your handling code here:
		String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del nuevo usuario: ", "Nuevo Usuario", JOptionPane.QUESTION_MESSAGE);
		if (nombre == null) return;
		nombre = nombre.trim();
		if(nombre.isEmpty()){
			JOptionPane.showMessageDialog(this, "El nombre del usuario no puede estar vacio..", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
		String[] opciones = {"prioridad alta", "prioridad media", "prioridad baja"};
    
		String tipo = (String) JOptionPane.showInputDialog(this, 
			"Seleccione la prioridad para " + nombre + ":",
			"Seleccionar Prioridad",
			JOptionPane.QUESTION_MESSAGE,
			null, 
			opciones, 
			opciones[0] 
		);
		
		if (tipo != null) {
		    
		    if (MiTablaHash.existeUsuario(nombre)) {
			JOptionPane.showMessageDialog(this, "El usuario '" + nombre + "' ya existe.", "Error", JOptionPane.WARNING_MESSAGE);
		    } else {
			Usuario nuevo = new Usuario(nombre, tipo);
			modeloUsuarios.addElement(nuevo.getNombre() + " (" + nuevo.getTipo() + ")");
			JOptionPane.showMessageDialog(this, "Usuario registrado con éxito.");
		    }
		}
        }//GEN-LAST:event_AgregarUsuarioActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new principal().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton AgregarUsuario;
        private javax.swing.JButton CargarCSV;
        private javax.swing.JButton EliminarUsuario;
        private javax.swing.JList<String> ListadeUsuarios;
        private javax.swing.JPanel MostrarArbol;
        private javax.swing.JPanel VistaLista;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTable jTable1;
        // End of variables declaration//GEN-END:variables
}
